# .bashrc

set -o vi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi


export ECN_ENVIRONMENT=${USER}_bzx
export TERM="screen-256color"
export DJANGO_SETTINGS_MODULE=intranet.batsint.settings


export VISUAL="/home/nmorse/.local/bin/nvim"
export EDITOR="$VISUAL"

# The following line allows for tab completion with git commands, branches, etc.
if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

# User specific aliases and functions
alias myssh='eval $(ssh-agent) && ssh-add && ln -sf ${SSH_AUTH_SOCK} ~/.ssh/ssh_auth_sock'
alias nodes="cd ~/db/nodes && ls"
alias cdp="cd ~/source/python"
alias st="git status"
alias ga="git add -A"
alias jump="ssh ccc-jump01.us.cboe.net"
alias jumpuk="ssh scolinjh1.uk.cboe.net"
alias mylogs="git log --author $(whoami) --stat"
alias npmrun='NODE_OPTIONS="--max-old-space-size=4096" npm run server'
alias refresh_claude_keys="source ~/setup_claude_env.sh"
alias bsp="bootstrap_parallel.py -d -p 1500 --skip-kafka --skip-kudu --skip-vault --skip-snowflake std"
alias aws="/usr/bin/aws"

alias vim="~/.local/bin/nvim"

alias sn='syseng-nodectl'
alias snl='syseng-nodectl --environment=syseng-production list '
alias sne='syseng-nodectl --environment=syseng-production update --message "Read Only" --edit '
function snu() {
    syseng-nodectl --environment=syseng-production update --message "$1" --edit $2
}
alias sgb="syseng-grains-browser grain-search --node "

alias build_hosts="syseng-nodectl list | jq -r '.[] | select(.role_name == \"bats-build-incredibuild\" and .pre_production == false) | .name'"
alias jump_hosts="syseng-nodectl list | jq -r '.[] | select(.role_name == \"jump-host\" and .pre_production == false) | .name'"

function pt() {
    pytest -sv --disable-warnings $@
}

function ptx() {
    pytest -svx --disable-warnings $@
}

# fzf git checkout branch
fcb() {
  local branches branch
  branches=$(git --no-pager branch -vv) &&
  branch=$(echo "$branches" | fzf +m) &&
  git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")
}

# fzf cd to selected directory
fcd() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}

function bs() {
    if [ "$1"  = "all" ]; then
        bootstrap_parallel.py -dv std;
    else
        DBENV=$(whoami)_$1
        if [ "$#" -lt 2  ]; then
            DBTYPES="mongo";
            shift 1
        else
            DBTYPES=$2
            shift 2
        fi

        cmd="bootstrap.py -dfq --db-types=$DBTYPES --skip-vault --skip-kudu --skip-docs --skip-kafka --no-analyze --skip-snowflake $@ $DBENV"
        echo $cmd && eval $cmd
    fi
}

cdir () {
    mkdir -p -- "$1" && cd -P -- "$1"
}

goto() {
    cd "$(find $1 -printf '%h')"
}

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

export PS1="\[\e[32m\]\@\[\e[m\] \[\e[35m\]\h\[\e[m\] \[\e[31m\]\w\[\e[m\]\n\[\e[1;34m\](\`parse_git_branch\`)\[\e[m\] >> "

# shortcut for sending files to Windows
function sendme()
{
    echo $HOSTNAME':'$PWD'/'$1 'File emailed from linux' | nail -a $1 -s container-files nmorse@cboe.com
}

function sendyou()
{
    if [[ $# < 2 ]] ; then
        echo "Need both file and email address"
    else
        echo $HOSTNAME':'$PWD'/'$1 'File emailed from linux' | nail -a $1 -s container-files $2
    fi
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [ -f ~/source/util/bash_completions.sh ]; then
        export BSQL_ENVIRONMENT_FILTER="^${USER}_|^[^_]+\$"
       . ~/source/util/bash_completions.sh
fi

# auto completion for nosetests (tam)
. ~/source/util/pytest_complete
